# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 503c4a09c28a107890401b87af98b28e473ecefe78bf228738053934a6b9e602d02ac5fc0c8d4d8ff9742a57b91274606b54f386afac25e0058227d6b1e28514

test:
  secret_key_base: 26c63da048502e131c45cea60353f9242ad055d649bfd1b4434c6817ad6f4be492ff05e8ee46fcf1050b5f77148d45d1c35de5c1deda7883550c58e68e588a7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
